### ISSUE TITLE
DESIGN: NETWORK POLICY IN SR-IOV CNI PLUGIN

### ISSUE THREAD

**Issue by saberlilydian** [k8snetworkplumbingwg/sriov-cni#101]
## Problem
A [network policy](https://kubernetes.io/docs/concepts/services-networking/network-policies/) in Kubernetes is a specification of how groups of pods are allowed to communicate with each other and other network endpoints. [Multus](https://github.com/intel/multus-cni) enables attaching multiple network interfaces to pods. For now SR-IOV CNI is supposed to be used with Multus but SR-IOV CNI doesn’t support Network Policy. However Network Policy should be applied to all CNI plugin otherwise there will be a security issue: the pod can still access another pod through SR-IOV network which is forbidden to be accessed by other plugins. For example, Multus is used and Calico which supporting Network Policy is the default plugin. Pod1 is forbidden to access Pod2 by Network Policy. Then Pod1 can’t access Pod2 through eth0 which is created by Calico.  But Pod1 can still access Pod2 through net1 which is created by SR-IOV CNI because Calico can’t control SR-IOV network,.
```
+------------+           +--------------+
+    Pod1    +           +    Pod2      +
+            +           +              +
+    +-------+           +-------+      +
+    + eth0  +---  X  ---+ eth0  +      +
+    +-------+           +-------+      +
+            +           +              +
+    +-------+           +-------+      +
+    + net1  +-----------+ net1  +      +
+    +-------+           +-------+      +
+------------+           +--------------+
```
## Proposal
There is an [embedded switch](https://docs.microsoft.com/en-us/windows-hardware/drivers/network/nic-switches) in the SR-IOV capable NIC and it’s used to forward network traffic between the physical port on the adapter and internal virtual ports. By utilizing DPDK or [TC flower](https://www.netdevconf.org/2.2/papers/horman-tcflower-talk.pdf), network policy can be offloaded to the embedded switch.
![Picture1](https://user-images.githubusercontent.com/7694942/64580679-c809b280-d3b9-11e9-9265-8cbd4dc439d4.png)

## Proposed changes
1. Add a Network Policy Driver. Network Policy Driver should be a separate entity. It can be agents running on Kubernetes nodes (aka hosts). DPDK and TC flower can be implementations of the Network Policy Driver. The base Network Policy Driver need to watch kube-apiserver network policy and pod status. 
```
+-------------------------------------------------+
+                  kube-apiserver                 +
+  +---------------------+   +----------------+   +
+  +   network policy    +   +  pod status    +   +
+  +-----------+---------+   +---------+------+   +
+--------------|-----------------------|----------+
               |                       |
               |        watch          |
               |                       |
        +------+-----------------------+-----+ 
        +                                    +
        +        Network Policy Driver       +
        +                                    +
        +  +----------+   +--------------+   +
        +  +   DPDK   +   +  TC flower   +   +
        +  +----------+   +--------------+   +
        +------------------------------------+
```

2. Offloading network policy to embedded switch by the implementation of Network Policy Driver. All network policy can be mapped to DPDK [testpmd](https://doc.dpdk.org/guides/testpmd_app_ug/testpmd_funcs.html#flow-rules-management) and [TC flower](http://man7.org/linux/man-pages/man8/tc-flower.8.html) as following: (Testpmd is an example application built with DPDK SDK. The features implemented by testpmd can also be implemeted by our application.)
![networkPolicy](https://user-images.githubusercontent.com/7694942/64582335-dce94480-d3bf-11e9-98a7-43a4a587caef.PNG)

3. DPDK:
Need to use user space driver igb_uio as PF driver and then configure VF through PF. Because PF is not bound to kernel space driver, PF won’t have a name. Need to implement existing functions in SR-IOV CNI plugin again because kernel space driver is not used. The following table shows how to implement the existing functions:

Function | Implementation
-- | --
Set VF’s MAC | testpmd> set vf mac addr (port_id) (vf_id) (XX:XX:XX:XX:XX:XX)  By default, MAC address will be given to VF. If user needs a specific MAC address, he will need to unbind and rebind vf’s driver to change MAC address.
Set VF’s vlan | testpmd> set vf vlan insert (port_id) (vf_id) (vlan_id)
Set VF’s vlanQos | Need to investigate and should be supported by DPDK. If not, we can request DPDK community to implement this feature.
Set VF spoofcheck | testpmd> set vf vlan antispoof (port_id) (vf_id) (on\|off)testpmd> set vf mac antispoof  (port_id) (vf_id) (on\|off)
Set VF trust | Need to investigate and should be supported by DPDK. If not, we can request DPDK community to implement this feature.
Set VF max_tx_rate | testpmd> set vf tx max-bandwidth (port_id) (vf_id) (max_bandwidth)

4. TC flower
Can reuse kernel space driver and little code changes to SR-IOV CNI existing code. But require the NIC has the NETIF_F_HW_TC feature enabled and implements ndo_setup_tc. 
To enable TC hardware offload:
    ethtool -K eth0 hw-tc-offload on
To check whether hw-tc-offload has been enabled:
    ethtool -k eth0 | grep hw-tc-offload

## Benefits
1. Network traffic is processed on the embedded switch and thus CPU resource is saved. Usually Network Policies are implemented by iptables which makes network packets to go through kernel space. And CPU will be used to process network traffic if iptables is used.
2. It can accelerate the speed of processing network traffic if most of the packets should be dropped. Such as DDOS.
3. The security issue described in the section “Problem” won’t occur.

**Comment by zshi-redhat** [comment]
@saberlilydian thanks for the detailed issue description and proposal!
I think this is a very useful case for SR-IOV and worth a thoroughly discussion.
Few questions to help me understand the proposed solution:
1) what would be the Network Policy Driver?  Will it be a function implemented in SR-IOV CNI or it'll be a separate entity?
2) If the network policies are applied to PF interface, then how it guarantee the security and isolation between VFs(from same PF) that are attached to different pods?
3) How this differs from [OVS Hardware offload with SR-IOV technology](https://docs.google.com/document/d/11uBezjSZg5b2g6VNs2mugGrgK5ZX9c-Xirj6XL_acjM/edit)?

**Comment by saberlilydian** [comment]
@zshi-redhat thank you for your feedback! For your questions:
1. Network Policy Driver should be a separate entity. It can be agents running on Kubernetes nodes.
2. PF and VFs are connected by the embedded switch. Through PF we can offload network policies (DPDK flows or TC filters) to the embedded switch. Some traffic can be matched based on the DPDK flows or TC filters and then block those traffic or allow those traffic.
3. This proposal is using DPDK and TC flower for offloading and [OVS Hardware offload with SR-IOV technology](https://docs.google.com/document/d/11uBezjSZg5b2g6VNs2mugGrgK5ZX9c-Xirj6XL_acjM/edit) is using switchdev for offloading.

**Comment by Levovar** [comment]
"otherwise there will be a security issue: the pod can still access another pod through SR-IOV network which is forbidden to be accessed by other plugins. "
not saying network policies wouldn't be a good thing but: you always have the possibility to separate different networks with VLANs
if you don't want two Pods, possibly belonging to different namespaces and applications to be able to communicate with each other, just put them on different VLANs (and foc configure your switch appropriately)

**Comment by saberlilydian** [comment]
@Levovar thank you for your comment! But I think VLAN can't solve the issue because traffic can be ingress and egress in Network Policy. By using VLAN, ingress and egress will be blocked or allowed simultaneously. However we can block the ingress while allow the egress in Network Policy.

**Comment by Levovar** [comment]
@saberlilydian yeah sure, but is that a use-case? A Pod wants to talk to another Pod on another network, but wouldn't like to receive the answers? :)
NetworkPolicies are of course useful, because you can dynamically control the rules, I was only commenting that it is entirely possible to satisfy strit TelCo security requirements with thecurrent architecture too (and with some network planning).

Reg the implementation concept: when you say "embedded switch" are you referring to SmartNICs / iNICs, i.e. NICs including a programmable unit (FPGA)? If yes, how would such a feature work on conventional NICs?

have you considered some eBPF "magic" as a possible implementation alternative?

**Comment by adrianchiris** [comment]
@saberlilydian , a couple of questions.

1.  when using DPDK, what will block a user from removing those rules from within the container ?
  looking [here](https://github.com/intel/sriov-network-device-plugin/tree/master/docs/dpdk#privileges) it seems that in some scenarios a pod needs to run in privileged mode.

2. What is the expected behaviour when k8s network policy is updated

3. looking at previous comments i see :

> PF and VFs are connected by the embedded switch. Through PF we can offload network policies (DPDK flows or TC filters) to the embedded switch. Some traffic can be matched based on the DPDK flows or TC filters and then block those traffic or allow those traffic.

in SR-IOV legacy mode applying a TC rule on a PF netdev and having it affect VFs seems to me vendor specific as to my understanding a PF is just another port in the embedded switch, same as VF. Why would configuring rules on PortA affect traffic of PortB?

Since switchdev is not being used, then it would make sense to apply the TC rules on the VF itself.

@Levovar 

> Reg the implementation concept: when you say "embedded switch" are you referring to SmartNICs / iNICs, i.e. NICs including a programmable unit (FPGA)? If yes, how would such a feature work on conventional NICs?
To my understanding, if the NIC does not support offloading of TC flower rules then all packet processing will be done in kernel (which kinda defeats the purpose of using SR-IOV).  SmartNICs/iNICS (Intelligent NIC ?) contain hardware that is able to offload these rules, whether by a programmable logic (i.e FPGA) or ASIC.

**Comment by moshe010** [comment]
In 4. TC flower you say:
 "Can reuse kernel space driver and little code changes" Does this means you need to modify the kernel driver to make it work?

**Comment by saberlilydian** [comment]
@Levovar Network Policy can block traffic to specific protocol and port. For example, TCP and port 8888. I think this can't be supported by configuring VLAN.

SR-IOV enabled switch has embedded switch which is used to forward the traffic between PF and VFs.  

eBPF can be another implementation for Network Policy Driver. But processing in the hardware will be quicker than eBPF.

**Comment by saberlilydian** [comment]
@adrianchiris Thank you for your comments! For your questions:
1. As I replied to @zshi-redhat, Network Policy Driver should be an agent in the Kubernetes nodes (aka host). And this agent should be a DPDK application when DPDK is used. Besides PF is used to set Network Policy and PF is also in host. So we don't need to run DPDK in Pod.
2. Network Policy Driver should watch Kubernetes Network Policy. If Network Policy is updated, Network Policy Driver should also update the DPDK flows or TC filters set in the NIC.
3. We should support this setting Network Policy through both PF and VF. I will adjust the proposal.

**Comment by saberlilydian** [comment]
@moshe010 Thank you for your comments! I mean little changes to SR-IOV CNI existing code. I will adjust the proposal. Sorry for misleading!

**Comment by adrianchiris** [comment]
@saberlilydian thanks for addressing the comments,

Some follow up comments:

> As I replied to @zshi-redhat, Network Policy Driver should be an agent in the Kubernetes nodes (aka host). And this agent should be a DPDK application when DPDK is used. Besides PF is used to set Network Policy and PF is also in host. So we don't need to run DPDK in Pod.

I probably have some knowledge gaps here, but in case i want to run a DPDK application in the container (DPDK app runs on the VF), what will prevent the user from removing the flows previously programmed by the PF in the host ? my concern here is a security concern.
for vfio-pci we are OK but to my understanding igb-uio requires root privileges in order to run DPDK app in the container.

> Network Policy Driver should watch Kubernetes Network Policy. If Network Policy is updated, Network Policy Driver should also update the DPDK flows or TC filters set in the NIC.

Here i was referring to how the rules are intended to be modified by the DPDK/TC network policy driver and whether or not there may be a point in time when transitioning from network policy A to network policy B where something that should have been blocked is temporarily allowed.
I guess Network policy translates (by the policy driver) to individual flow rules that shall be replaced on policy change? 
anyway, thats implementation details...

**Comment by saberlilydian** [comment]
@adrianchiris For your questions:
1. We can propose only use vfio-pci because the security issue exists on driver igb_uio.
2. Yes, the individual flow rules should be replaced on policy change.

**Comment by zshi-redhat** [comment]
@saberlilydian are you still interested in moving this forward?

**Comment by saberlilydian** [comment]
@zshi-redhat Yes, absolutely! I have made a presentation about this PR on OpenInfra 
2019 and the link is below: https://www.openstack.org/videos/summits/shanghai-2019/starlingx-hardware-acceleration-driven-network-policies-on-edge

**Comment by zshi-redhat** [comment]
> @zshi-redhat Yes, absolutely! I have made a presentation about this PR on OpenInfra
> 2019 and the link is below: https://www.openstack.org/videos/summits/shanghai-2019/starlingx-hardware-acceleration-driven-network-policies-on-edge

@saberlilydian thanks for the link!  Did you also have demo utilizing TC? Have you done any comparison between the two implementations (rte_flow or tc) and pros/cons? would you mind join our biweekly [meeting](https://docs.google.com/document/d/1sJQMHbxZdeYJPgAWK1aSt6yzZ4K_8es7woVIrwinVwI/edit#) for a discussion ()?

**Comment by martinkennelly** [comment]
@saberlilydian do you want to continue this discussion? I'd be interested in hearing pros/cons of rte_flow / tc. I will close this Issue if I do not get a response in a months time. Thank you for this input.
